language: node_js
node_js:
  - node
install:
  - npm ci
script:
  - npm test
deploy:
  provider: npm
  email:
    secure: DK6WM7ScyQqaloBKk9FJ4P4YDK/7EzRL1DXhwvuOPpi7j28WRsAtWePmFgoEZLIjB50ypDRGGB08zilB+rOdkgQipolPwl/dKHIAZlCAwCglKQCs5eVX5DWCvXsgP9s0fox0xMEPItDrcqycueyglvAHdBa7vmz8+zZPGAoBMe8Md8bhd7I+YFvXV9egEWMB6fefNDIpBJiSraA4wSOL4wTP4rzFYihu0chrori+M9dtu34iUOnS3Jap/a8jVx2qkRU4zCQmG+LJUGFebofQGI0hiihp6s1EBpSG6UOkr7OZa1fONRMpBI93qDvQoBYYvMQVn8j/MfCIg3zdw+YGlsK1mPctUj6S4aRmGN5JphTYXL1kdXtwKg+NjeI8ukCvzDIFIv9bLy9UIBiSs2ZNkMEI6BWso6BFdA9/R0mm5SHN2Z0wAzg9s3GxRvcrIdSmz9As5dramL0od6BWK7uffZfYpmQCyUIwYUvXa7tGIa/RQs/w9IuU/8lIIUQ0btu2E46lRnvX+gU5/dkPSfsn2zv9LhuaAGRuC+nh/FpHc8NIz0N8fN9EFdxXF7UzhdWZdShaFCfWT3kPqDuOx814BZst5Kn/OP2F39KAmk0V4PtGM1A2Yo+TUL5LJaREBt+MIw2ctJ4cgHJGdb+/nJC0Hfo5pRpfAEYtquiF9BgHFzo=
  api_key:
    secure: Zbsreg8ggAY2aT3PeqqjF8XZOV1eGOKAfyUrs8YCuAv4KKtwOsPAT8GyMdFSSuTPYabrPKXKCXro71HDvd8HxmRoChHVYEzUGRcPleqpE7EbEPMQL7R8OvRMgs47Cq5zmu2MvjEDkZ6zd6/OhexXORcPkKxDpQL7TyeQxaWxlDMvOC1fMIDn+2FRPw8AvRV0c36udU0cDHbnaP0soJ2hx2LYAqSC/JPDvRqHCJllbfMOOICz4msQF488aMyNO25EhUYMacKNXnbR80R/j/oTdq9mkBjMc7Ny2SPxa/wVXaebyv2pAFS7EqC2syK4scpyR/aqFSLRI9ayWoirdKI7MjoWz+DXlE+7suGKPkEWkyRatko0SVAKOdfjtTYSvny+AtiXmrtTeL6L0HqLBrw13Ech0xHpmYjoxCtBkRjrzYgJUWpV7xBg2lAgga3jfL3XyibEetoXZChwzZkhDIQez3tTf/MIq4zJrQTeommnh6qFS7+9QYV2vlJqgo4dxY3CiOf4f4A1ZHrcwp5WQB/lJRqhUhCjVrOW89ObiN8w06zccwq3A0pSj3820Kvizw1JijfLk16VC4vNde56QkAyTJbIuVGpcMDZr0fTY6xPD6eSOcX65JPUtxFzeSTVXayKnpa745p5FEgoeFyW4Z1D5J1emAJS+25/yBK/7bBKRms=
  on:
    tags: true
    repo: weijunyu/passport-openidconnect
