language: node_js
node_js:
- node
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: junyuwei@gmail.com
  api_key:
    secure: Zbsreg8ggAY2aT3PeqqjF8XZOV1eGOKAfyUrs8YCuAv4KKtwOsPAT8GyMdFSSuTPYabrPKXKCXro71HDvd8HxmRoChHVYEzUGRcPleqpE7EbEPMQL7R8OvRMgs47Cq5zmu2MvjEDkZ6zd6/OhexXORcPkKxDpQL7TyeQxaWxlDMvOC1fMIDn+2FRPw8AvRV0c36udU0cDHbnaP0soJ2hx2LYAqSC/JPDvRqHCJllbfMOOICz4msQF488aMyNO25EhUYMacKNXnbR80R/j/oTdq9mkBjMc7Ny2SPxa/wVXaebyv2pAFS7EqC2syK4scpyR/aqFSLRI9ayWoirdKI7MjoWz+DXlE+7suGKPkEWkyRatko0SVAKOdfjtTYSvny+AtiXmrtTeL6L0HqLBrw13Ech0xHpmYjoxCtBkRjrzYgJUWpV7xBg2lAgga3jfL3XyibEetoXZChwzZkhDIQez3tTf/MIq4zJrQTeommnh6qFS7+9QYV2vlJqgo4dxY3CiOf4f4A1ZHrcwp5WQB/lJRqhUhCjVrOW89ObiN8w06zccwq3A0pSj3820Kvizw1JijfLk16VC4vNde56QkAyTJbIuVGpcMDZr0fTY6xPD6eSOcX65JPUtxFzeSTVXayKnpa745p5FEgoeFyW4Z1D5J1emAJS+25/yBK/7bBKRms=
  on:
    tags: true
    repo: weijunyu/passport-openidconnect
